namespace:
  name: prod
 
image:
  repository: techtrends
  tag: lastest
  pullPolicy: Always

replicaCount: 5

service:
  port: 7111
  
resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
